# The contents of this file are parsed and made available as
# via `site.*`. So for example, {{ site.title }} can be used
# in a template to get the contents of the `title` key.
title: The Division 2
subtitle: 
github_link: https://github.com/gamestrafe/thedivision2
url: https://thedivision2.gamestrafe.com

google_tag_manager_id: GTM-MKS5N2K

# Default value, if no other is defined
meta:
    description: All info about Tom Clancy's The Division 2 that you could ever need.

# Insert your disqus shortname
#disqus:
#    shortname: